version: '3.8'
services:
  node-server:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'

  web-server:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - '8080:80'
